platform:
    - x64

cache:
    - '%LocalAppData%\.opam'

install:
    - npm install -g rimraf
    - npm install -g yarn
    - git submodule update --init --recursive
    - npm install esy-bash
    - npm install esy-ocaml/FastReplaceString.git#9450b6
    - node scripts/bootstrap/copy-fastreplacestring.js
    - appveyor-retry yarn run bootstrap:esy-install
    - npm run bootstrap:install-opam
    - npm run bootstrap:install-dependencies

build_script:
# Reset %PATH% to avoid cygwin DLL conflicts with cause
# *** fatal error - cygheap base mismatch detected
    - echo $PATH
    - set PATH=C:\Windows\System32;C:\Windows;C:\Program Files (x86)\nodejs;C:\Users\appveyor\AppData\Roaming\npm;C:\projects\esy\node_modules\esy-bash\.cygwin\bin
    - npm run bootstrap:build
    - C:\projects\esy\_release\_build\default\esy\bin\esyCommand.exe --help

test_script:
# TODO: Incorporate existing test suite - will we need to migrate from bash -> something else?
    - git clone https://github.com/esy-ocaml/esy-reason-project C:\esy-reason-project
    - cd esy-reason-project
    - appveyor-retry C:\projects\esy\_release\_build\default\esy\bin\esyCommand.exe install

artifacts:
    - path: _release
      name: esy-windows

test: off
