platform:
    - x64

cache:
    - '%LocalAppData%\.opam'

install:
    - npm install -g rimraf
    - npm install -g yarn
    - git submodule update
    - git submodule init
    - yarn install
    - yarn run temp:find-npm
    - yarn run bootstrap:install-opam
    - yarn run bootstrap:install-dependencies
    - yarn run bootstrap:esy-install:install

build_script:
# Reset %PATH% to avoid cygwin DLL conflicts with cause
# *** fatal error - cygheap base mismatch detected
    - set PATH=C:\Windows\System32;C:\Windows;C:\Program Files (x86)\nodejs;C:\Users\appveyor\AppData\Roaming\npm
    - yarn run temp:cygwin:check-dll
    - yarn run bootstrap:build

artifacts:
    - path: _release
      name: esy-windows

test: off
