platform:
    - x86
    - x64

install:
    - npm install

environment:
  NPM_TOKEN:
    secure: pNdFuPuA8RB67Dxjn4u/Om+NoCy851jnz+YDTflZgej0LIT/+HC0r545wgS5msIr

build_script:
    - npm build-bootstrapped-windows

test: off
