platform:
    - x64

cache:
    - '%LocalAppData%\.opam'

install:
    - npm install -g rimraf
    - rimraf C:\cygwin
    - rimraf C:\cygwin64
    - rimraf C:\mingw-w64
    - rimraf C:\MinGw
    - npm install
    - npm run bootstrap:install-opam
    - npm run bootstrap:install-dependencies

build_script:
    - npm run cygwin:check-dll
    - npm run bootstrap:build

artifacts:
    - path: _release
      name: esy-windows

test: off
