platform:
    - x86
    - x64

install:
    - npm install esy-cygwin
    - cygwin-bash ./bootstrap-windows-install-opam-dependencies.sh

build_script:
    - git submodule init
    - git submodule update
    - cygwin-bash jbuilder build

test: off
