platform:
    - x64

cache:
    - '%LocalAppData%\.opam'

install:
    - npm install -g rimraf
    - npm install -g yarn
    - rimraf C:\cygwin
    - rimraf C:\cygwin64
    - rimraf C:\mingw-w64
    - rimraf C:\MinGw
    - npm install
    - npm run bootstrap:install-opam
    - npm run bootstrap:install-dependencies

build_script:
# Reset %PATH% to avoid cygwin DLL conflicts with cause
# *** fatal error - cygheap base mismatch detected
    - npm run temp:find-npm
    - set PATH=C:\Windows\System32;C:\Windows;C:\Program Files (x86)\nodejs
    - npm run temp:cygwin:check-dll
    - npm run bootstrap:build

artifacts:
    - path: _release
      name: esy-windows

test: off
