platform:
    - x86
    - x64

install:
    - npm install esy-cygwin
    - cygwin-bash ./bootstrap-windows-install-opam-dependencies.sh

build_script:
    - cygwin-bash make bootstrap
    - cygwin-bash make bootstrap
    - cygwin-bash make build-release
    - npm install -g _release

test: off
