opam install ocaml-migrate-parsetree --yes
opam install reason --yes
opam install cmdliner --yes
opam install lwt --yes
opam install menhir --yes
opam install ppx_let --yes
opam install ppx_deriving_yojson --yes
opam install lwt_ppx --yes
opam install yojson --yes
opam install bos --yes
opam install re --yes
